---
name: bazel

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python_version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.platform }}
    env:
      BAZEL_PYTHON_VERSION: ${{ matrix.python_version }}
    steps:
      - uses: actions/checkout@v4

      - name: Build again
        run: bazel test //... -k
